spring:
 datasource:
  url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
  username: ${PGUSER}
  password: ${PGPASSWORD}
  server.port:${PORT:8080}
 jpa:
  open-in-view: false
  hibernate:
   ddl-auto: validate #Use create in the first time, then, change to validate
